# CLOMonitor metadata file
# This file must be located at the root of the repository

# Checks exemptions
exemptions:
  - check: artifacthub_badge # Check identifier (see https://github.com/cncf/clomonitor/blob/main/docs/checks.md#exemptions)
    reason: "Project is a library and does not create an artifact" # Justification of this exemption (mandatory, it will be displayed on the UI)
